# Change these first
owner: giventofly # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: bookmarks.josemoreira.pt
    url: https://bookmarks.josemoreira.pt
  - name: JAM's Bonsai 
    url: https://jambonsai.com
  - name: josemoreira.pt
    url: https://josemoreira.pt
  - name: Linkding Jam
    url: https://links.josemoreira.pt
  - name: outnow
    url: https://outnow.josemoreira.pt
  - name: redis.josemoreira.pt
    url: https://redis.josemoreira.pt
    expectedStatusCodes:
      - 200
      - 400
  - name: rss.josemoreira.pt
    url: https://rss.josemoreira.pt
  - name: screenshots.josemoreira.pt
    url: https://screenshots.josemoreira.pt
  - name: snek board
    url: https://snekboard.com
  - name: snek forge
    url: https://snekforge.com
  - name: stick a snek
    url: https://stickasnek.com
  - name: stats.stickasnek.com
    url: https://stats.stickasnek.com
  - name: suggestions
    url: https://suggestions.josemoreira.pt
  - name: snek timeline
    url: https://snektimeline.com
  - name: the pipe stays lit
    url: https://thepipestayslit.com
  - name: wp.josemoreira.pt
    url: https://wp.josemoreira.pt
  - name: snekverse
    url: https://snek.josemoreira.pt
  - name: why snek?
    url: https://whysnek.com
  - name: snekregret
    url: https://snekregret.com
  - name: snek forge
    url: https://snekforge.com
  - name: snek culture
    url: https://snekculture.com

  
delay: 2000

assignees:
  - giventofly

status-website:
  #baseUrl: /uptime # "repo" is your repository name
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.josemoreira.pt
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/giventofly/uptime/refs/heads/master/assets/Custom_SNEK_yellow_bg_clearer.png
  name: Upty 
  #introTitle: some uptime tracking, with dracula theme
  #introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */2 * * *"

user-agent: github-checker
