# Change these first
owner: giventofly # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: josemoreira.pt
    url: https://www.josemoreira.pt
  - name: weather
    url: https://weather.josemoreira.pt
  - name: snek timeline
    url: https://snektimeline.com
  - name: the pipe stays lit
    url: https://thepipestayslit.com
  - name: bookmarks.josemoreira.pt
    url: https://bookbmarks.josemoreira.pt
  - name: wp.josemoreira.pt
    url: https://wp.josemoreira.pt
  - name: xs.josemoreira.pt
    url: https://xs.josemoreira.pt
  
delay: 5000

assignees:
  - giventofly

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.josemoreira.pt
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/giventofly/uptime/refs/heads/master/assets/Custom_SNEK_yellow_bg_clearer.png
  name: Upty 
  introTitle: some uptime tracking, with dracula theme
  #introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: JAM
      href: https://josemoreira.pt
theme: https://raw.githubusercontent.com/giventofly/uptime/refs/heads/master/assets/dracula.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

user-agent: github-checker